language: go

services:
  - docker

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx


matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - go get -u github.com/golang/dep/...
  - dep ensure

jobs:
  include:
    - stage: gofmt
      script:
        - if [ -n "$(gofmt -s -l . | grep -v "vendor")" ]; then diff -u <(echo -n) <(gofmt -d $(gofmt -s -l . | grep -v "vendor")); fi
    - stage: "tests"
      name: "Unit Tests"
      script:
        - go test -v -race $(go list ./... | grep -v "/vendor/")
        - go get github.com/haya14busa/goverage
        - goverage -coverprofile=coverage.txt ./...
        - bash <(curl -s https://codecov.io/bash)
    - name: "Docker build"
      script:
        - docker build -t codex/svalinn:local .
        - docker run -d -p 8181 codex/svalinn:local
        - docker ps -a
    - name: "Integration Tests"
      script:
        - docker images