language: go

go:
  - 1.11.x
  - tip

os:
  - linux
  - osx

services:
  - docker

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make style codecov

jobs:
  include:
    - stage: integration
      name: "Integration Tests"
      script:
        - make it