[[constraint]]
  name = "github.com/Comcast/codex"
  version= "v0.2.5"

[[override]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[override]]
  name = "github.com/ugorji/go"
  revision = "e5e69e061d4f7ee3a69b793cf9c1b41afe21918e"

[prune]
  go-tests = true
  unused-packages = true
